# Generated by Django 5.0 on 2023-12-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extend', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='website/logo')),
                ('copyright', models.BooleanField(default=False)),
            ],
        ),
    ]
