# Generated by Django 5.0 on 2023-12-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_idata_facebook_idata_linkedin_idata_twitter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idata',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idata',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idata',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
