# Generated by Django 5.0 on 2023-12-22 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_idata_facebook_alter_idata_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='address',
            new_name='number',
        ),
        migrations.CreateModel(
            name='about_paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=2000)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.about')),
            ],
        ),
    ]
