# Generated by Django 5.0 on 2023-12-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_rename_address_phone_number_about_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_paragraph',
            old_name='address',
            new_name='paragraph',
        ),
    ]
