# Generated by Django 5.0 on 2023-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_address_about_paragraph_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsettler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
