# Generated by Django 5.0 on 2023-12-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsettler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='protfolio')),
                ('disc', models.TextField(max_length=2000)),
            ],
        ),
    ]
