# Generated by Django 5.0 on 2023-12-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
