# Generated by Django 5.0 on 2023-12-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='course/poster')),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('per', models.CharField(blank=True, choices=[('year', 'year'), ('month', 'month'), ('once', 'once')], max_length=255)),
                ('r1', models.IntegerField(blank=True)),
                ('r15', models.IntegerField(blank=True)),
                ('r2', models.IntegerField(blank=True)),
                ('r25', models.IntegerField(blank=True)),
                ('r3', models.IntegerField(blank=True)),
                ('r35', models.IntegerField(blank=True)),
                ('r4', models.IntegerField(blank=True)),
                ('r45', models.IntegerField(blank=True)),
                ('r5', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.category')),
            ],
        ),
    ]
