# Generated by Django 5.0 on 2023-12-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_price_alter_course_r1_alter_course_r15_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disc',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
