# Generated by Django 5.0 on 2023-12-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
