# Generated by Django 5.0 on 2023-12-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
